### ISSUE TITLE
PDF cover sheet language is confusing

### ISSUE THREAD

**Issue by nicholascaldwell** [vote-forward/votefwd#255]
Summary:
User reports that page 2 (containing 5 voter names and addresses) of a 25 page packet is actually printing as page 22.

Steps to Reproduce:
Needs to be reproduced

Expected Results:
Page 2 prints as page 2 

Actual Results:
Page 2 prints as page 22

Customer reports (Ticket 1410): 

> "Thought it might be useful for you to know that the second page of my 25-person list, which should have been pg.2 of the full kit, was actually pg.22. 
> 
> Not a huge deal, except I didn't realize I was missing 5 names until I was almost done and then discovered the 2nd page plus additional letters. "

Need to reproduce and create a test case.

**Comment by jimwebb** [comment]
This is expected behavior by the system. The cover page to a 25-voter packet only has 20 names; the last 5 names are shown in a second cover page.
